### ISSUE TITLE
Overflowing with longer text

### ISSUE THREAD

**Issue by matixmatix** [sir-dunxalot/ember-tooltips#105]
I'm experiencing overflow issues:

![image](https://cloud.githubusercontent.com/assets/273660/19628905/e9935ae8-9968-11e6-9354-8c2175fc5570.png)

Any suggestions on how to make it automatically stretch?

I'm using Bootstrap. The code:

```handlebars
{{#each-in filters as |_ filter|}}
    <button class="btn btn-filter {{if (get this filter.param) 'active'}}" {{action 'toggleFilter' filter.param}}>
      {{#if filter.tooltip}}
        {{#tooltip-on-element}}
          {{filter.tooltip}}
        {{/tooltip-on-element}}
      {{/if}}
      {{filter.name}}
    </button>
  {{/each-in}}
```

**Comment by a15n** [comment]
I've never seen that before. The tooltip has a max-width set here (https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/styles/addon.scss#L29) and since we don't set any overflow attributes it inherits the normal breaking behavior (https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap).

My guess is that you may have a class that our tooltip uses that is overriding the default breaking behavior. If you want to override that other classes behavior this may work.

```
.ember-tooltip {
  overflow-wrap: normal !important;
}
```
