### ISSUE TITLE
Hidden Popover causes body to stretch on initial page load

### ISSUE THREAD

**Issue by ChrizzDF** [sir-dunxalot/ember-tooltips#111]
Hi everyone,

In this view (Screenshot) I use a popover that causes the body to stretch after the page was loaded.
If I then hover over the info icon, the popup appears correctly above the target element and the body is no longer stretched.

![popover-issue](https://cloud.githubusercontent.com/assets/3121574/20099404/9a46f29a-a5b8-11e6-9d40-dfb8adf4fc96.jpg)

My code:
```
<i class="fa fa-info-circle info" id="test-popover"></i>
{{#popover-on-element target="#test-popover"}}
  Some content
{{/popover-on-element}}
```

Any thoughts on this?

Update:
I added an additional line of CSS and for now it works like a charm:
```
.ember-tooltip, .ember-popover {
position: fixed !important;
}
```

**Comment by sir-dunxalot** [comment]
Does `position: fixed;` not make tooltips appear in the wrong place on the page? This might work when tooltips are children of `body` but that will probably break is the developer places tooltips on any other element. I am interested in finding a solution for this though.

**Comment by aarkus7** [comment]
I'm experiencing a similar problem with tooltips - it either enlarges the container or goes off the page.

Setting to position: fixed kind of solves the issue, except that scrolling the page leaves the tooltip behind.

**Comment by aarkus7** [comment]
I'm experiencing a similar problem with tooltips - even with keepInWindow: true, they either push the container out or push out of the window

**Comment by sir-dunxalot** [comment]
See #82 - I believe this is related even if it's not exactly the same issue. Will know more when a PR is created and we can test this out.

**Comment by nagits** [comment]
I have a similar bug. When I shrink the window, horizontal scroll appears because of the hidden popover (tooltip) at the right side: position of the hidden popover doesn't update when I shrink the window (it ok), but it still renders (with opacity: 0).

https://webm.red/Dv7X.webm

**Comment by chrcha** [comment]
Hey, running 2.9.2 this happens to me as well. Not sure why, but some times and for some of the tooltips(-on-element) the display is absolute instead of fixed which results in what the title says. The suggested patch (aka. forcing display: fixed) corrects that behavior. I cannot reproduce the bug consistently; haven't figured out the pattern yet. Thought I'd just let you know it's still there...

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
