### ISSUE TITLE
Additional exceptions with triggerTooltipTargetEvent

### ISSUE THREAD

**Issue by ryanlabouve** [sir-dunxalot/ember-tooltips#135]
The errors from [getTooltipFromBody](https://github.com/sir-dunxalot/ember-tooltips/blob/dad31a5e5fb04bf85fbc933efbfee3154b5a00d9/test-support/helpers/ember-tooltips.js#L13) were helpful in hunting down why [assertTooltipVisible](https://github.com/sir-dunxalot/ember-tooltips/blob/dad31a5e5fb04bf85fbc933efbfee3154b5a00d9/test-support/helpers/ember-tooltips.js#L80) was not behaving as I expected.

Could the same type of error messages be added here on [triggerTooltipTargetEvent](https://github.com/sir-dunxalot/ember-tooltips/blob/dad31a5e5fb04bf85fbc933efbfee3154b5a00d9/test-support/helpers/ember-tooltips.js#L22) when the target is not found?

Happy to help with this if useful.

**Comment by a15n** [comment]
which "target" are you referring to? The `triggerTooltipTargetEvent` accepts a jquery element as the first parameter.

**Comment by ryanlabouve** [comment]
Sorry, target as in the tooltip's target.

So, if `$element` or `options.selected` was not found, would be nice to have an error message like `triggerTooltopTargetEvent: the element you passed in was not a tooltip target`.

**Comment by a15n** [comment]
`$element` should be passed in, but if it isn't the current way the error throws ("[You used undefined](https://github.com/sir-dunxalot/ember-tooltips/blob/dad31a5e5fb04bf85fbc933efbfee3154b5a00d9/test-support/helpers/ember-tooltips.js#L26)") could definitely be improved.

Also there are places in our tests where this helper is used on $elements that are not the tooltip target. These are in the popover tests where we click the popover, popover interior, target interior, etc. Because of this we can't demand that the $element **must** be the tooltip's target. Maybe a check to see if it is a jquery element would be best.

But the basics of this issue, make the errors more helpful, are good. If you could make a PR for this that'd be great. Thanks.

**Comment by maxfierke** [comment]
I think the spirit of this is handled more robustly in 3.x, so closing.
