### ISSUE TITLE
constraints not passable to ember-tether in 2.4+

### ISSUE THREAD

**Issue by hemp** [sir-dunxalot/ember-tooltips#140]
With lazy rendering, `constraints` is not a passable property anymore.  I think adding it to this list here might be a quick fix, but wanted to open this issue for discussion:  https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/components/lazy-render-wrapper.js#L21

The goal here is sometimes the tooltip needs to fall inside of the scrollParent rather than the viewport:

```
// component.js
tooltipConstraints: [{
  to: 'scrollParent',
  attachment: 'together',
  pin: ['left', 'right']
}],

// template.hbs
{{#tooltip-on-element class="..." constraints=tooltipConstraints}}
```

One caveat is given the caret/arrow is a pseudo element, that ends up needing a top level style for tooltips which leverage the underlying tether `constraint` property to adjust the arrow accordingly.

In the end, I'm looking to leverage this instead of Bootstrap 3's tooltip library (which does caret/arrow adjustment and scrollParent type stuff) and happy to help if I can.

**Comment by a15n** [comment]
you're correct in that passing the constraint property to the list of `passableProperties` is the correct way to pass it thru to the tether-tooltip-on-component.

But you'll likely run into the issue you've identified which is that the caret/arrow currently only supports top-center, right-center, bottom-center, or left-center positioning. Here is the PR that is working on that. @jcward10 just emailed me so I know he's currently working on it, if you were able to help him that'd be wonderful

https://github.com/sir-dunxalot/ember-tooltips/pull/103

@hemp would adding `constraint` as a pass-through property fix this issue or is it also dependent on positioning the caret correctly?

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
