### ISSUE TITLE
Using tooltip-on-element with customized `tagName`

### ISSUE THREAD

**Issue by Azdaroth** [sir-dunxalot/ember-tooltips#147]
I think since 2.4.0 version `tagName` is by default empty (since introduction of lazy-render-wrapper component). This is causing problems when extending `tooltip-on-element` component and providing `tagName` (and `tagName` cannot be empty when using e.g. `classNameBindings`) and the tooltip doesn't work at all. Here is the difference between generated HTMLs, without `tagName`:

``` html
<div tabindex="0" role="tooltip" id="ember356" class="ember-tether ember-tooltip ember-tooltip-or-popover-slide ember-view ember-tooltip-or-popover-element ember-tooltip-or-popover-element-attached-center ember-tooltip-or-popover-target-attached-center ember-tooltip-or-popover-element-attached-bottom ember-tooltip-or-popover-target-attached-top" aria-hidden="true" data-tether-enabled="false" style="top: 0px; left: 0px; position: absolute; transform: translateX(473px) translateY(3px) translateZ(0px);">        

  Content

</div>
```

and with `tagName`:

``` html
<div id="ember338" class="ember-view ember-tooltip-or-popover-target ember-tooltip-or-popover-element-attached-bottom ember-tooltip-or-popover-element-attached-center ember-tooltip-or-popover-target-attached-top ember-tooltip-or-popover-target-attached-center" aria-describedby="ember356" tabindex="0">
  <div tabindex="0" role="tooltip" id="ember356" class="ember-tether ember-tooltip ember-tooltip-or-popover-slide ember-view ember-tooltip-or-popover-element ember-tooltip-or-popover-element-attached-bottom ember-tooltip-or-popover-element-attached-center ember-tooltip-or-popover-target-attached-top ember-tooltip-or-popover-target-attached-center" aria-hidden="true" data-tether-enabled="false" style="top: 0px; left: 0px; position: absolute; transform: translateX(473px) translateY(76px) translateZ(0px);">    
   
    Content

  </div>
</div>
```

So this outer wrapper is clearly a problem here,  blocking the inner div and firing events when hovering on it as we no longer hover on this element, but on the outer one. 

The only solution I've found so far to this problem is providing `target` attribute. Any other idea how to make it work without providing `target` for every single usage of the component?

**Comment by a15n** [comment]
The `tooltip-on-element` and sibling components all extend the `lazy-render-wrapper` component, which is tagless. We use a tagless component because it should only serve as a wrapper/observer component that renders the real tooltip component when the target component has been interacted with (mouseenter, focus, or click). 

IIRC I chose to use a tagless component because passing `id='foo'` to a tagged component and then passing it through to the real component would produce two components with the id of `foo`. 

I don't think you'll be able to use the top-level components to extend *and* provide a `tagName` to the extension.

You should be able to achieve the desired affect by instead extending `tether-tooltip-on-element`. This component is what you were using before 2.4.0 and hasn't had any changes apart from a name change. However this approach doesn't support lazy-rendering. But if you're not facing any performance issues with tons of tooltips then that shouldn't be a concern.

**Comment by Azdaroth** [comment]
Ok, thanks for the answer, I think it's pretty clear now. I guess this issue can be closed then.
