### ISSUE TITLE
isShown doesn't come back to false when tooltip hides on mouseleave

### ISSUE THREAD

**Issue by nag5000** [sir-dunxalot/ember-tooltips#170]
$E._debugContainerKey
-> "component:popover-on-component"

1. ```$E.set('isShown', true)``` - OK, I see the popover.
2. Hide popover using mouse (mouseenter, mouseleave) - OK
3. ```$E.get('isShown') // true (!?)``` - FAIL.
4. (additionally, as a consequence) ```$E.set('isShown', true)``` - FAIL, I don't see the popover.

But everything is good with `isShown` in "component:tether-popover-on-component" (tether-tooltip-and-popover): all these steps work as expected if $E is "component:tether-popover-on-component".

So, problem with `isShown` in lazy-render-wrapper.

**Comment by nagits** [comment]
I think, `isShown` should be passed from lazy-render-wrapper to tether-tooltip-and-popover separately from `passedPropertiesObject`, to provide two-way binding of `isShown` between this components.

**Comment by a15n** [comment]
that would fix it. One other alternative if you don't need lazy-rendering is to use the `tether-popover-on-component` instead of `popover-on-component`. That will bypass the lazy-render-wrapper and not have lazy rendering capabilities

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
