### ISSUE TITLE
using 'tooltipEvent' and 'tooltipVisibility' tooltip does not close when property set false

### ISSUE THREAD

**Issue by chrismllr** [sir-dunxalot/ember-tooltips#18]
Having an issue using `tooltipEvent` and `tooltipVisibility` based on a property... When the property is false (in my case, setting false on deactivate) it does not close the tooltip, and it is stranded on the page.

Is there a method I could call on deactivate to close any tooltips that may be open?

**Comment by sir-dunxalot** [comment]
What is `tooltipEvent` set to in this case?

**Comment by chrismllr** [comment]
`click`...  I had tried `manual`, and was getting an error `Uncaught TypeError: Ember.default.$(...)[options.event] is not a function`..

Here is a snippet...

```
    {{#as-calendar/occurrence
      tooltipEvent='click' tooltipVisibility='showDialog'}}

      <h1 style={{titleStyle}}>{{occurrence.title}}</h1>

      {{#tooltip-on-parent place='bottom' spacing=15}}
        <div class="modal__tooltip">
          <div class="container">
            
          </div>
        </div>
      {{/tooltip-on-parent}}
    {{/as-calendar/occurrence}}
```

**Comment by sir-dunxalot** [comment]
Ok, thanks for the info. `tooltipVisibility` will only take effect when `tooltipEvent='manual'`. It seems like that is throwing an unexpected error, which is the core issue here. I'll look into why this is happening.

**Comment by chrismllr** [comment]
Thanks, FYI  Ember is v1.13.7

**Comment by chrismllr** [comment]
@sir-dunxalot Any progress here?

**Comment by sir-dunxalot** [comment]
Sorry, haven't been able to dig into it. Using tooltipVisibility with anything other than `tooltipEvent='manual'` isn't supported right now. It's not a perfect setup but it's functional.

To manage hiding and showing the tooltip you can call methods on the tooltip object within said component. For example, `this.get('tooltip').show()` or  `this.get('tooltip').hide()`. In fact, you can do anything on that object that you can do with the [tooltip dependency library](https://github.com/darsain/tooltip). So you could use the component's events in combination with this to fake the events.

Also, on second glance, the above code looks like you're binding a string to `tooltipVisibility` rather than the actual boolean property, which wouldn't require quotation marks. Is this intended?

**Comment by chrismllr** [comment]
@sir-dunxalot Sorry for the delay.. That's a great observation.. whew, that would be embarrassing! Let me try it out and I'll report back soon.. Thanks for your assessment

**Comment by chrismllr** [comment]
That Indeed was it. *retreats to dark corner* Closing!

**Comment by sir-dunxalot** [comment]
No worries, man! I know it's not an optimal solution - I've been thinking about how to make it fool proof (not calling you a fool haha).

Happy to help.
