### ISSUE TITLE
Tooltip ignores duration when used with enableLazyRendering and event='none'

### ISSUE THREAD

**Issue by manuel-reil** [sir-dunxalot/ember-tooltips#185]
I am using it as follows:

`{{#tooltip-on-component event='none' enableLazyRendering=true duration=2500 isShown=isCanceled}} ...`

I let it show programmatically via `isShown`. It should stay there for 2500ms (`duration`).
This works as intended once a remove `enableLazyRendering=true`.

Seems like `isShown` wins against `duration`.

Thanks,
Manuel

**Comment by sir-dunxalot** [comment]
Hi Manuel,

Thank you for debugging the issue. There does appear to be a conflict between `isShown` and `duration`. However, I'm not sure what the solution should be. Would you expect the duration to set `isShown` to `false` after 2500ms?

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
