### ISSUE TITLE
expect style test helpers

### ISSUE THREAD

**Issue by et** [sir-dunxalot/ember-tooltips#193]
Great work on this plugin, it works extremely well. Also enjoy the test helpers you've provided.
I was wondering if there a way to use the test helpers with an expect style syntax (i.e. where I don't have an `assert` object available.

I would think, it could essentially just drop the `assert` prefix from all the test helpers and look like the following:

```js
import {
 tooltipRendered,
} from 'appname/tests/helpers/ember-tooltips';

it 'shows a tooltip', function() {
  expect(tooltipRendered).to.be(true);
});
```

Or if you didn't want to support new test helper functions, just have each [test helper](https://github.com/sir-dunxalot/ember-tooltips/blob/master/test-support/helpers/ember-tooltips.js) return a boolean if an `assert` object is not provided.

Thoughts? I'm happy to submit a PR for either of the scenarios 😄

**Comment by sir-dunxalot** [comment]
As you are probably already thinking, this library will primarily offer `assert()`-based helpers since the Ember community embraces `assert()` by default.

However, I am open to a PR that lets `expect()`-preferring developers use a function from each existing test helper, similar to how your code example highlights.

However, we could not introduce any breaking changes with this functionality.

**Comment by sir-dunxalot** [comment]
Sorry, meant to 'comment' not 'comment and close'.

**Comment by et** [comment]
Thanks @sir-dunxalot. I've since moved to the dark side with React 😢 so I no longer have a need for this.
Since this issue didn't get any support from other people, I'm going to close this issue for housekeeping purposes.
