### ISSUE TITLE
Add global enableLazyRendering option

### ISSUE THREAD

**Issue by Ramblurr** [sir-dunxalot/ember-tooltips#195]
Since `enableLazyRendering` will become the default, it would be nice if we could specify an environment config to enable it by default. Otherwise we have to litter `enableLazyRendering=true` all over our codebase.

**Comment by ChrizzDF** [comment]
Until there will be a default setting, you can also just create the component and override the value for now.

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released and `enableLazyRendering` is built-in (and not optional).

`3.0.0` brings significant improvements to reliability, simplicity, and extendability. You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you notice any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
