### ISSUE TITLE
Issue with position absolute

### ISSUE THREAD

**Issue by okachynskyy** [sir-dunxalot/ember-tooltips#201]
Here is [demo](https://ember-twiddle.com/afc9a6ff8fdd653c28e5317913bb9bd9?openFiles=templates.application.hbs%2C):

1) Open twiddle (don't hover on the green box)
![step1](https://cloud.githubusercontent.com/assets/16646570/26623567/d820b7fc-45f6-11e7-9873-32cb449b8d75.png)

2) Reduce window size
![step2](https://cloud.githubusercontent.com/assets/16646570/26623574/db18bdd8-45f6-11e7-9819-3cf41cfe09fe.png)
You should see growing horizontal scroll.

3) Hover on green box again
![step3](https://cloud.githubusercontent.com/assets/16646570/26623582/dd84145a-45f6-11e7-8078-bd7e734dd052.png)
Horizontal scroll should disappear.

Lazy loading doesn't help, because I have the same issue when I hover on element and then reduce window size (my body width keeps big before hover again).

**Comment by nsmith7989** [comment]
I'm having the same issue. 

I know this isn't a solid solution, but I ended up adding some override css:

```
[aria-hidden=true] {
  position: absolute !important;
  transform: none !important;
}```

**Comment by offirgolan** [comment]
Bump. 

The solution mentioned by @nsmith7989 works but destroys the out animation of the tooltip / popover. 

@sir-dunxalot with a lot of tooltips on multiple elements, hidden ones add extra whitespace to the end of the html body.

**Comment by okachynskyy** [comment]
@offirgolan, Here is my solution (based on solution from @nsmith7989):
`
[aria-hidden=true] {
  position: absolute !important;
  transform: none !important;
  visibility: hidden;
}
`

This style just remove disappearing animation but it works for me since this animation is not necessary and this solution does not add any extra whitespaces and does not stretches body width.

**Comment by GCheung55** [comment]
Is the position and transform being controlled by `ember-tether` or `tether`? I couldn't tell.

**Comment by GCheung55** [comment]
I'm seeing this as well with a lot of tooltips.

**Comment by GCheung55** [comment]
When I prevent the `stopTether` method from triggering `this.get('_tether').disable();` I cannot reproduce this issue. My understanding is that Tether.js will reposition on window resize, so I'm assuming disabling tether will prevent it from repositioning.

**Comment by FredUK** [comment]
I'm experiencing the same issue. 

A solution without messing with the CSS and aria-hidden attribute would be to when the tooltip disappears actually destroy its DOM element instead of just hiding it. (with LazyLoading set to true). 

One could argue that's not efficient as we might have to generate an identical element every time you over the same tooltip trigger but the overhead is minimal I believe if you have simple tooltips..

**Comment by mirague** [comment]
We, too, experience added whitespace at the bottom of our website after using this addon with a dozen or so tooltips. Will try out the CSS solution provided but ideally the elements are removed from the DOM when not visible, or at least (when idle) positioned in a place where they don't increase width or height of the document.

**Comment by mirague** [comment]
@sir-dunxalot What's your thoughts on this issue?

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
