### ISSUE TITLE
How to specify scroll parent?

### ISSUE THREAD

**Issue by varoot** [sir-dunxalot/ember-tooltips#202]
It seems currently there is no way to constraint the tooltip to a scroll parent (therefore the tooltips are rendered outside of scroll parent when the target is out of view). This may be related to #140 but I would prefer a simpler way than passing the whole constraint settings.

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If this issue isn't automagically fixed by the upgrade, you might want to look into passing `popperOptions`, which is documented in the README.

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
