### ISSUE TITLE
Tooltip isn't repositioned when the target is

### ISSUE THREAD

**Issue by anehx** [sir-dunxalot/ember-tooltips#218]
If the target is repositioned by e.g getting filtered or whatever, the tooltip to it is not repositioned but just stays where it was before.

See [demo](https://ember-twiddle.com/ec74107b47f71140bd0a31d15706e3de).

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
