### ISSUE TITLE
Adding a link inside the tooltip

### ISSUE THREAD

**Issue by kehphin** [sir-dunxalot/ember-tooltips#51]
Hi, 

I didn't see any demo examples of a clickable link in the content of a tooltip - is this currently possible? I tried adding an anchor tag to the content but it's not clickable, presumably because the focus is not on the tooltip?

Thanks, and great addon!

**Comment by sir-dunxalot** [comment]
The `{{tooltip-on-parent}}` component should allow for any HTML to be rendered inside a tooltip, including HTMLBars ([see here](https://github.com/sir-dunxalot/ember-tooltips#using-as-a-component)).

Is the issue that the user cannot hover over the tooltip because the tooltip disappears once the trigger element is not being interacted with?

**Comment by kehphin** [comment]
I have the following tooltip toggled by click:

```
{{#my-component}}
      {{#tooltip-on-parent event='click'}}
        <a href='google.com'>Test</a>
      {{/tooltip-on-parent}}
    {{/my-component}}
```

The issue is that when I try to click on the tooltip link comment, the tooltip closes because I am clicking outside the trigger element.

**Comment by sir-dunxalot** [comment]
Ok, got it. I'm not immediately sure what we could implement to support this for every event type. As a stopgap, you could set the `tooltipShowOn` and `tooltipHideOn` events individually (the actually property names for the `{{tooltip-on-parent}}` component is `showOn` and `hideOn`). If `hideOn='none'` or something like that you could not hide the tooltip once it has been shown and, thus, allow the user to click the tooltip.

You can see an example under [events](https://github.com/sir-dunxalot/ember-tooltips#events) - see the second code block.


I wonder if a tooltip is even the right UI device to use in this situation?

**Comment by kehphin** [comment]
I tried the `showOn` and `hideOn` and it still wasn't working. After digging around, I discovered that it was because the tooltip has the `pointer-events: none` in its css, not allowing the user to interact with the tooltip.

I overwrote the css with:
```
.tooltip {
  pointer-events: all;
}

```
and it worked. I think a tooltip with a link is a legitimate use case - our use case is that the user hovers over the tooltip for basic info, and then they can click on a link in the tooltip for a more detailed page. Anyways, thanks for the quick responses!!

**Comment by sir-dunxalot** [comment]
Ok. I'll play around with what effect removing `pointer-events: none` will have on other tooltips and will get back to you.

**Comment by rwwagner90** [comment]
I also need support for being able to click a button, link, etc.

**Comment by sir-dunxalot** [comment]
So with release `1.0.0`, this issue still exists because clicking on a tooltip removes focus from the target element. So it seems like we're at the cross roads between maintaining accessibility and figuring out a good solution for this use case. I'm still planning on coming up with a solution for this.

**Comment by rwwagner90** [comment]
@sir-dunxalot the `pointer-events: all;` solution worked for me here.

**Comment by sir-dunxalot** [comment]
Ok, great! Do you think it's worth adding that to the addon's CSS?

**Comment by rwwagner90** [comment]
@sir-dunxalot yeah, I think adding it, or at least an option for it, might be good.

**Comment by sir-dunxalot** [comment]
Sounds good. Are you just applying it to the `.tooltip` class?

**Comment by rwwagner90** [comment]
Yeah, just applying to `.tooltip`.

**Comment by MiguelMadero** [comment]
> the tooltip closes because I am clicking outside the trigger element.

It sounds like a possible solution could be not to close if we clicked inside of the tooltip.

**Comment by MiguelMadero** [comment]
I did a quick POC and it seems like this works if we only `hide` the tooltip on focusout if the original event wasn't on the tooltip itself. See the [ember-tooltips changes](https://github.com/ember-samples/ember-tooltips-withactions-sample) and a sample [POC](https://github.com/ember-samples/ember-tooltips-withactions-sample). There is also a [running sample](https://ember-samples.github.io/ember-tooltips-withactions-sample/).

**Comment by rwwagner90** [comment]
@MiguelMadero does using `pointer-events: all` not work for you?

**Comment by MiguelMadero** [comment]
I don't think that's enough, the problem with that is that the tooltip still looses focus. I could set it to close/open on click and that works as well, but has a different behavior, clicking outside of the tooltip won't close it either.

**Comment by rwwagner90** [comment]
@MiguelMadero what sort of interactions are you trying to do inside the tooltip?

`pointer-events: all` works for me and does close if I click outside the tooltip.

**Comment by MiguelMadero** [comment]
@rwwagner90 selecting text, clicking a link or clicking a button. What configuration do you have for the `tooltip-on-element`? Maybe I'm missing some combination of event and hideOn that makes it not close on lostFocus, but still close when you click outside.... This is what I have: 

```
{{#tooltip-on-element event="click" hideOn="none"}}
```

I tried a few others, I think having `event="click" and hideOn="click"` allowed for clicking on the tooltip, but it wouldn't close when clicking outside.

**Comment by rwwagner90** [comment]
@MiguelMadero we're manually creating tooltips using the `renderTooltip`, which seems to no longer be a thing. 

@sir-dunxalot it appears only components are available now and `renderTooltip` was removed from utils. Is this true?

**Comment by MiguelMadero** [comment]
@rwwagner90 I'm not familiar with `renderTooltip`, but that might be why it worked. With components, we subscribe to `blur` on the element that triggers the tooltip and close the tooltip. I'm guessing that `renderTooltip` didn't have that behavior since we didn't have an element to subscribe.

**Comment by rwwagner90** [comment]
@MiguelMadero yeah, I'm not familiar with the new functionality. We have to manually add the tootltips, so this new component way won't work for us anyway.

**Comment by sir-dunxalot** [comment]
`renderTooltip` was removed from 1.0.0 releases, correct. What's the use case in which you wouldn't be able to use any of the components? Maybe there is a way we can make this library work for you.

**Comment by rwwagner90** [comment]
@sir-dunxalot we are currently using `renderTooltip` and setting up html strings to add as tooltips. We have to do it this way because we are adding tooltips to another third party library, http://fullcalendar.io/, and we are displaying tooltips when you click an event on the calendar.

It may be possible to manually use the htmlbars compiler and create some html strings, but I was unable to figure out how to do that. If that worked, we could use the components probably.

**Comment by MiguelMadero** [comment]
We have a similar use case for an external lib. We still don't have a solution for that. cc: @andrew-zenefits @kazuzenefits.

**Comment by andrew-zenefits** [comment]
Thanks for bringing me into this discussion @MiguelMadero. As far as the "similar use case for an external lib" I'll let @kazuzenefits speak to that because he understands the use case better.

As for the original question of this thread, "can I put a clickable link into a tooltip", a few thoughts. Duncan said "I wonder if a tooltip is even the right UI device to use in this situation?" and I agree with the question. It seems like there should be two components to achieve this...
* tooltip
  * not interactive
  * used for showing small amounts of helper text (we're considering a 140 character limit at Zenefits)
  * black background, white text 
  * this library already covers that 100%
* popover
  * interactive: interior can include links and other interactive components (radio buttons, select, youTube videos, etc)
  * used for showing interactive elements (see pic)
  * different UI than a tooltip to signify that interaction is possible. This could be standardized by this library or by developers extending a base popover component and adding their own handling for title, body, yields, and styles (I prefer the second approach for customization)

I've been playing around with different ways of achieving popover functionality and have been unable to get it to work. @sir-dunxalot I have some free cycles and would be happy to build a solution but would need some guidance on the best way to do this. 


<img width="750" alt="screen shot 2016-06-22 at 1 38 56 pm" src="https://cloud.githubusercontent.com/assets/8782940/16282697/bddd3d92-387e-11e6-878f-d3793746d232.png">

**Comment by sir-dunxalot** [comment]
Good stuff @andrew-zenefits. Thanks for the length reply. This discussion would overlap with #77 regarding adding a popover component to this library.

I think it would be a great addition and I'm happy to provide details and guidance with some preliminary thoughts. Let me know how you'd like to proceed. Are you more interested in discussing the functionality/requirements side of thing or actually digging into the addon to to see how you might implement a popover solution?

This doesn't solve the external lib/`renderTooltips()` discussion so I'm interested to see how we can support those use cases.

**Comment by andrew-zenefits** [comment]
I'll move my conversation over to https://github.com/sir-dunxalot/ember-tooltips/issues/77. thanks Duncan

**Comment by sir-dunxalot** [comment]
Sounds good. Anyone else who is interested in popovers: we will discuss in #77.

Good work with all of the inputs and ideas so far!

**Comment by sir-dunxalot** [comment]
The ability to add clickable links in popovers now exists thanks to #92.
