### ISSUE TITLE
Tooltip inconsistent inside Bootstrap Modal

### ISSUE THREAD

**Issue by ehubbell** [sir-dunxalot/ember-tooltips#69]
Hey There,

Trying to use tooltips inside a Modal however they're not showing up consistently. If I open the modal and then hover over a tooltip, the tooltip isn't getting attached to the target element. However, when I open the inspector and then 'click' on the tooltip it gets activated next to the element. Do you know how I can get this to activate within the modal correctly every time?

``` HTML
      <div class='col-xs-12'>
        <label>Title</label>
          <span id='event_title' class='icon icon-question-mark'>
            {{#tooltip-on-element target='#event_title' side='right' spacing=20}}Enter a short, descriptive event title.{{/tooltip-on-element}}
          </span>
        {{focused-input value=model.title type="text" placeholder="Trip to the Mountains!" required=true}}
      </div>
```

And a couple images showing the two tooltips getting initialized:
![screenshot 2016-05-23 13 57 52](https://cloud.githubusercontent.com/assets/4422450/15482879/4049fe34-20ef-11e6-98b9-68b4b6d6d017.png)
![screenshot 2016-05-23 14 01 24](https://cloud.githubusercontent.com/assets/4422450/15482878/4043449a-20ef-11e6-98f4-b8e6e75b4c5c.png)

**Comment by jatt** [comment]
Same applies to bootstrap dropdowns, so probably it has something to do with absolute positioning. I'll post here if I find something.

**Comment by sir-dunxalot** [comment]
Hey guys,

So this is likely something to with an issue in [ember-tether](https://github.com/yapplabs/ember-tether)'s positioning. More specifically, [tether](https://github.com/HubSpot/tether/issues?page=2&q=is%3Aissue+is%3Aopen) might have an issue. I looked the issue and didn't see anything obvious.

Maybe something stands out to you?

And @ehubbell, in the example above, does the modal have `position` (like `absolute` or `fixed`)? And does the target (the '?' icon) also have a `position` of some kind?

**Comment by jatt** [comment]
I was able to fix the problem by setting `updateFor=isDropdownOpen`, where `isDropdownOpen` is a variable that controls display of my custom ember wrapper around bootstrap dropdown. So, looks like this:

1. Target is dropdown, it's hidden and rendered.
2. Ember-tooltips renders hidden tooltip, since target is hidden, ember-tether sets its position to [0, 0].
3. Out-of-the-box when tooltip is activated, it will be just displayed, but not re-rendered, we get the bug described here.

Possible solutions:
1. Make ember-tether re-calculate position right before toggling display on (looks like correct way)
2. What I did, make ember-tooltips re-render when target position is changed (easier to do)

**Comment by sir-dunxalot** [comment]
Got it. That makes sense.

Just so I make sure I understand correctly... A target element is in the DOM and the tooltip is attached. However, the target element hasn't yet been positioned or displayed? Thus, when it is displayed the tooltip previously rendered was not attached to the element's correct position because the element didn't have a position and/or the position changed?

**Comment by jatt** [comment]
Yes, you are right.

**Comment by andrew-zenefits** [comment]
@jatt @ehubbell did you guys happen to find a solution for this? I've come across the same problem.

**Comment by ehubbell** [comment]
I actually switched to another library that let me append the tooltip to another divs ID. Lib called emberstrap. Has a bunch of bootstrap js replacements for ember that work well.

Eric (from iPhone)
720.212.1434

On Jul 12, 2016, at 21:14, Andrew Scheuermann <notifications@github.com> wrote:

@jatt @ehubbell did you guys happen to find a solution for this? I've come across the same problem.
