### ISSUE TITLE
rename tooltip class to ember-tooltip

### ISSUE THREAD

**Issue by andrew-zenefits** [sir-dunxalot/ember-tooltips#79]
We have a massive codebase and are migrating to ember-tooltips for all our tooltip needs. In the past people have created `tooltip` classes for their one-off tooltip components. This means that a plain inclusion of this library will introduce many style conflicts to existing tooltips, and vice-versa. Right now our options are...

1) Fork our own PR with a temporary fix (extended the components, additional className for specificity, and add this in the library's styles `.ember-tooltip.tooltip`). We would need to keep this fork until we've deprecated all of our existing `.tooltip` class reliant components and instance.
2) Upgrade this library to use `.ember-tooltip` classes everywhere instead of `.tooltip`. 

It seems that more specificity in naming conventions is better and that if this library were to use `.ember-tooltip` there would be less chance of similar roadblocks for large companies hoping to use it.

If this is an acceptable solution I can address it.

@MiguelMadero ^

**Comment by sir-dunxalot** [comment]
I think 2) seems like an acceptable solution. This issue came up once before with #15. An `.ember-tooltip` class namespace would be a stronger solution to that issue than just `.tooltip` so I'm in favor!

This would be a backwards incompatible styling change but I think that's ok if we offer good release notes for the change.

**Comment by MiguelMadero** [comment]
Thanks for tagging me. In addition to 2, I think this is a good emerging convention to have a one to one mapping between your component names and classes. If we decided to follow that `tooltip-on-element` may be a better name. 

Regardless of the name chosen, if we wanted to minimize the impact we could have two separate releases:

1. Do a patch release (1.0.1 if done now) with both classes, all of the styles would be on `tooltip-on-element`, but the `.tooltip` class will still be applied by default in case someone is styling that explicitly to target it instead. Unfortunately, it's hard to raise deprecation warnings for something like this and we can't assume everyone is using sasslint. So we would have to rely on release notes. 
2. Do a major release (2.0.0 if done now) with the same, but the flag turned-off or removed, ppl may still opt-in on the old behavior by explicitly adding the class if they don't want to refactor their css rules.

**Comment by andrew-zenefits** [comment]
Regarding the 1-1 mapping of components and classnames, *all* of the styles are shared between the `tooltip-on-element` and the `tooltip-on-component`. If this is the case we should decide on a shareable class name. I feel like `ember-tooltip` is a pretty good solution but would be open to different names.

In references to number 1 @MiguelMadero do you mean that we should keep the `tooltip` class in the classNames property but refactor so that all the styles are applied through `ember-tooltip` or whatever we choose?

PS: @sir-dunxalot why do we need `tooltip-on-component`? The default target property inside of `tooltip-on-element` looks up the parentElement's ID which means that it works that same way as finding the parentView's ID. I tested it and they both seemed to work (we're on Ember 1.13).

**Comment by andrew-zenefits** [comment]
I just ran tests before making any changes and there are three tests failing. I'll make sure to not break any more.

![screen shot 2016-06-29 at 10 20 29 am](https://cloud.githubusercontent.com/assets/8782940/16461810/3771335c-3de3-11e6-8e88-8b29f3791084.png)

**Comment by sir-dunxalot** [comment]
`{{tooltip-on-component}}` grabs the parent view's element's ID (not the parent element's ID). This is useful when the developer can't place the tooltip immediately inside the element of a component. For example, a component might have a layout with several elements surrounding the `{{yield}}` block, but the tooltip needs to be rendered on the component's element. Thus, `{{tooltip-on-component}}` skips a couple of levels of parent elements.

It's a minor function but it can make your life much easier in a few situations.

**Comment by andrew-zenefits** [comment]
Thanks for the explanation. Makes perfect sense.

Here is the PR for this issue https://github.com/sir-dunxalot/ember-tooltips/pull/80

**Comment by MiguelMadero** [comment]
> the styles are shared between the tooltip-on-element and the tooltip-on-component. 

tooltip-on-component inherits from tooltip-on-element. The final rendered component could have two classes, but we can keep the elements on the base. At least that's the "popular" but poorly documented convention..... 

> I feel like ember-tooltip is a pretty good solution but would be open to different names.

The reason for using the component name is because component names are already unique for any given app, e.g. the container can only have a single component with a given name, so the convention piggybacks from that to extend that to CSS. This doesn't really enforces anything, it just makes it less likely to happen. There is more tooling that's coming that is following this convention, but actually enforcing uniqueness, that's still far, but keeping this conventions now could help once the tooling is ready....

> we should keep the tooltip class in the classNames property but refactor so that all the styles are applied through ember-tooltip or whatever we choose?

Yes, this is mainly for backwards compatibility in case someone else that doesn't have this problem can upgrade. For us or others with that problem, could go to the next major version or opt-out. This might be overkill depending on how many users depend on this addon.

**Comment by andrew-zenefits** [comment]
@sir-dunxalot, @MiguelMadero and I chatted and we think that the most future-proof, "embery" way of doing this would be to rename every `tooltip` class to `tooltip-on-element`. In the PR I rename them to `ember-tooltips`. I can do whichever you prefer.

**Comment by sir-dunxalot** [comment]
So we seem to sit at the cross roads between the best emberish way and the best practical way here. Both have advantages. I would vote in favor of `.ember-tooltip` being the class simply because it detaches the styling from the implementation. In other words, there are many ways (components) to get to the same goal (a tooltip element).

For example, if we add back a utility function to generate tooltips on the fly in JS, that method should be named and should function independent of the element it's generating. Similarly, if we were to deprecate `tooltip-on-component` in the future (not saying we will, just talking hypothetically) that shouldn't really impact styling choices.

`.ember-tooltip` seems unique enough to me, given it's the libraries name, that I think we can get away with it instead of component-specific class names.

What do you think?

**Comment by andrew-zenefits** [comment]
I agree that '.ember-tooltip' is specific enough

**Comment by MiguelMadero** [comment]
Sounds good!

**Comment by sir-dunxalot** [comment]
Fixed by #80
